import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { getGenerationByShareToken } from '@/lib/server/generations';

// Public read-only view of a shared generation. 24-hour expiry enforced
// server-side in getGenerationByShareToken. Rendered with getServerSideProps
// so an expired / missing token returns a clean 404 or 410 without
// exposing the share_token to the client bundle.

export async function getServerSideProps({ params, res }) {
  const gen = await getGenerationByShareToken(params.token);
  if (!gen) {
    res.statusCode = 404;
    return { props: { state: 'not_found' } };
  }
  if (gen.expired) {
    res.statusCode = 410;
    return { props: { state: 'expired' } };
  }
  return {
    props: {
      state: 'ok',
      generation: {
        clientName: gen.client_name,
        targetMmp: gen.target_mmp,
        documents: gen.documents,
        createdAt: gen.created_at,
        shareExpiresAt: gen.share_expires_at,
      },
    },
  };
}

const TABS = [
  { key: 'runbook', label: 'Integration Runbook' },
  { key: 'faq', label: 'FAQ Document' },
  { key: 'checklist', label: 'Test Checklist' },
];

function relativeExpiry(iso) {
  if (!iso) return null;
  const ms = new Date(iso).getTime() - Date.now();
  if (ms <= 0) return 'expired';
  const hr = Math.round(ms / (60 * 60 * 1000));
  if (hr <= 1) return 'expires in <1h';
  if (hr < 48) return `expires in ${hr}h`;
  return `expires in ${Math.round(hr / 24)}d`;
}

function EmptyState({ title, subtitle }) {
  return (
    <div className="mx-auto flex min-h-screen max-w-xl flex-col items-center justify-center px-4 text-center">
      <h1 className="text-2xl font-semibold text-white">{title}</h1>
      <p className="mt-3 text-sm text-slate-400">{subtitle}</p>
    </div>
  );
}

export default function ShareTokenPage(props) {
  if (props.state === 'not_found') {
    return (
      <EmptyState
        title="Not found"
        subtitle="This share link doesn't match any generation. Ask whoever sent it for an up-to-date link."
      />
    );
  }
  if (props.state === 'expired') {
    return (
      <EmptyState
        title="This share link has expired"
        subtitle="Share links stay live for 24 hours. Ask the sender to regenerate and share a new one."
      />
    );
  }

  const { generation } = props;
  const [tab, setTab] = useState('runbook');
  const doc = generation.documents?.[tab] || '';
  const expiryLabel = relativeExpiry(generation.shareExpiresAt);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      <header className="border-b border-slate-800 bg-slate-950/80 backdrop-blur-sm">
        <div className="mx-auto max-w-3xl px-4 py-6 sm:px-6">
          <p className="text-xs uppercase tracking-wider text-indigo-400">
            Shared onboarding package
          </p>
          <h1 className="mt-1 text-2xl font-semibold">
            {generation.targetMmp || 'MMP'} onboarding for {generation.clientName}
          </h1>
          <p className="mt-2 text-xs text-slate-500">
            Read-only preview · {expiryLabel || 'expiry unknown'}
          </p>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-8 sm:px-6">
        <div className="mb-6 flex flex-wrap gap-2">
          {TABS.map((t) => (
            <button
              key={t.key}
              type="button"
              onClick={() => setTab(t.key)}
              className={`rounded-full border px-4 py-1.5 text-sm ${
                tab === t.key
                  ? 'border-indigo-500 bg-indigo-500/10 text-indigo-200'
                  : 'border-slate-700 bg-slate-900 text-slate-300 hover:border-slate-500'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>

        <article className="prose prose-invert prose-slate max-w-none rounded-xl border border-slate-800 bg-slate-900/40 p-5 sm:p-6">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{doc}</ReactMarkdown>
        </article>
      </main>

      <footer className="border-t border-slate-800 py-6 text-center text-xs text-slate-600">
        Generated by the MMP Onboarding Assistant
      </footer>
    </div>
  );
}
